FROM localhost/python:base as vectorizing

RUN pip install langchain langchain-community langchain-core psycopg2-binary \
  && pip install langchain-ollama pgvector

COPY rag_chat.py .

CMD ["python", "rag_chat.py"]
