FROM localhost/python:base as vectorizing

RUN pip install langchain-community langchain-text-splitters \
  && pip install langchain-ollama langchain-postgres \
  && pip install psycopg2-binary sqlalchemy \
  && pip install unstructured

COPY embedding.py .

CMD ["python", "embedding.py"]
