FROM localhost/python:base as vectorizing

RUN pip install langchain-community langchain-text-splitters langchain-ollama \
  && pip install psycopg2-binary sqlalchemy pgvector \
  && pip install unstructured

COPY embedding.py .

CMD ["python", "embedding.py"]
